### ISSUE TITLE
no proj4 on fish

### ISSUE THREAD

**Issue by aaschwanden** [pism/pism-builds#2]
@ckhroulev: This is not a new issue, I simply haven't paid attention to it:
When we compile PISM on fish without proj4 but use proj4 on the other machine, than time series that use area calculations will be different between fish and the other systems.

For consistency and comparability, we should add proj4 to the fish pism build script. The build_proj4() function in pleiades' build_pism.sh may work with no/little modifications.

**Comment by ckhroulev** [comment]
Sounds good.
